### ISSUE TITLE
File opening behavior config not working?

### ISSUE THREAD

**Issue by mlhetland** [qvacua/vimr#135]
Some of the configuration seems not to be working for me (Version 0.2.0 (20)). Primarily, the "Default Opening Behavior" dropdown dims when I try to use it, so I can't choose any of the options, leaving me with only new tabs.

Secondarily, I'm not clear on what unchecking the "Open Untitled Window [x] on re-activation" checkbox is supposed to do (though it doesn't seem to do anything?) … but I'd really like to be able to force VimR to open new files in the same window when I use, say, `open -a VimR somefile.txt` in the shell, like MacVim. Maybe I don't need a config for that (and I guess this isn't what the mentioned config options is for) – maybe I just need to use a different command? (I guess I could talk to the vim instance, etc., instead…)

**Comment by z0mbix** [comment]
I'm having this issue too. I'd rather not with tabs, but can't select any of these options.

**Comment by qvacua** [comment]
With Open Untitled Window [x] on re-activation you can control whether VimR should open a new window when you re-activate VimR by clicking on the VimR icon in the dock.

As for the `open -a VimR somefile.txt` opening the file in the same window, have a look at the command line tool which is bundled since 0.5.0. (for a documentation how to use it, cf https://github.com/qvacua/vimr/wiki/Command-Line-Tool
