### ISSUE TITLE
Doesn't run in OS X Yosemite

### ISSUE THREAD

**Issue by 191919** [qvacua/vimr#161]
vimr cannot create new documents or open any files.

Press Cmd+N: nothing happened.
Press Cmd+O: nothing happened after choosing a file.

Yosemite 10.10.1 on a MBP with Retina Display 15" Mid 2014.

**Comment by qvacua** [comment]
I use the exact same setting and I cannot reproduce the problem. Console output may be of help..

**Comment by 191919** [comment]
This is from console log:

1/21/15 13:17:11.078 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.user.501) Service "com.apple.xpc.launchd.unmanaged.Vim.52399" tried to hijack endpoint "/users/xx/desktop/vimr.app/contents/frameworks/macvimframework.framework/versions/a.vim" from owner: com.apple.xpc.launchd.unmanaged.Vim.52148

And this is what I got by running ./VimR in command line:

[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.

**Comment by qvacua** [comment]
All the warnings can be safely ignored. However, the first statement about `com.apple.xpc.launchd` seems to be a real problem... I'll try to find out more about this.

**Comment by 191919** [comment]
Any clue?

**Comment by qvacua** [comment]
No, I'm sorry. I cannot reproduce your problem. Do you have any other Vim process running in the background? What happens when you reboot/re-login?

(The warnings regarding TBObjcProperty you can safely ignore)

**Comment by kzahedi** [comment]
The problem are plugins, such as YouCompleteMe (other might cause the problem too). Vimr is also not working for me.

**Comment by 191919** [comment]
vimr 0.7.0 can create new documents or open existing ones.

**Comment by josecostamartins** [comment]
i can't open vimr in yosemite, tried both version 0.7.1 and the snapshot 20150424-1540, all give the same error:

2015-05-08 21:28:24.154 VimR[11908:3893154] Unknown class I in Interface Builder file at path /Users/josecostamartins/Downloads/VimR.app/Contents/Resources/Base.lproj/MainMenu.nib.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN ] 21:28:24:339 VRPropertyService readPropertiesFromUrl:-89 - There was an error opening file:///Users/josecostamartins/.vimr_rc: Error Domain=NSCocoaErrorDomain Code=260 "The file “.vimr_rc” couldn’t be opened because there is no such file." UserInfo=0x7fe969c42c60 {NSFilePath=/Users/josecostamartins/.vimr_rc, NSUnderlyingError=0x7fe969c12280 "The operation couldn’t be completed. No such file or directory"}
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
objc[11908]: Class VRPlugin is implemented in both /Users/josecostamartins/Downloads/VimR.app/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition and /Users/josecostamartins/Downloads/VimR.app/Contents/PlugIns/Markdown.vimr-plugin/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition. One of the two will be used. Which one is undefined.
[INFO ] 21:28:24:397 VRPluginManager loadPluginAtPath:-138 - Plugin com.qvacua.VimR.plugin.Markdown loaded.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 70: The type ? is not supported yet.
[WARN ] 21:28:25:068 VRPropertyService readPropertiesFromUrl:-89 - There was an error opening file:///Users/josecostamartins/.vimr_rc: Error Domain=NSCocoaErrorDomain Code=260 "The file “.vimr_rc” couldn’t be opened because there is no such file." UserInfo=0x7fe96c376ac0 {NSFilePath=/Users/josecostamartins/.vimr_rc, NSUnderlyingError=0x7fe96c376a10 "The operation couldn’t be completed. No such file or directory"}
Fatal Python error: PyThreadState_Get: no current thread
Vim: Caught deadly signal ABRT
Vim: Finished.

**Comment by jottr** [comment]
Just came here to report the exact same issue. 
VimR version 0.7.1-29 on Yosemite.

**Comment by qvacua** [comment]
> Fatal Python error: PyThreadState_Get: no current thread
> Vim: Caught deadly signal ABRT
> Vim: Finished.
Hm, this seems to be the old (known) python problem VimR has... I hope that I can address that problem at some point. However, since I don't do python, I don't know when I'll be able to do that...

**Comment by pstengel** [comment]
This recently starting happening to me as well. VimR launches without problems, but I cannot open files via the command line or the menu bar. I also cannot create a new document via the menu bar. I am on the latest El Capitan beta, but this bug was not triggered by an El Capitan update or any update for that matter -- it's been working without trouble up until a few days ago. I don't see any suspicious errors in the Console, nor on the command-line when I launch the app that way. Here is output from the CLI:

```
pstengel@HAL-9000 ~ $ /Applications/VimR.app/Contents/MacOS/VimR 
2015-08-28 09:13:47.609 VimR[95960:1726063] Unknown class I in Interface Builder file at path /Applications/VimR.app/Contents/Resources/Base.lproj/MainMenu.nib.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 71: The type ? is not supported yet.
## MESSAGE ABOVE REPEATED ##
objc[95960]: Class VRPlugin is implemented in both /Applications/VimR.app/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition and /Applications/VimR.app/Contents/PlugIns/Markdown.vimr-plugin/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition. One of the two will be used. Which one is undefined.
[INFO ] 09:13:47:742 VRPluginManager loadPluginAtPath:-138 - Plugin com.qvacua.VimR.plugin.Markdown loaded.
[WARN] -[TBObjcProperty determineTypeAndClass:] - 71: The type ? is not supported yet.
## MESSAGE ABOVE REPEATED ##
```

**Comment by pstengel** [comment]
I think I've figured this out: it's my `.bash_profile` causing the problem. Commenting out the environment initialization for `docker-machine` fixes the problem:

    eval "$(docker-machine env default)"

I'm not sure why this is causing a problem, but I'm assuming there's an error coming from this command when executed in the way that MacVim/VimR does it. Interestingly enough, MacVim works with this bash profile without commenting out the aforementioned line.

**Comment by pstengel** [comment]
`docker-machine` consumes `STDIN`, which is causing this problem. If anything is in your `.bash_profile`/`.bashrc`/etc that consumes `STDIN`, it prevents VimR from launching the bash command it needs to initialize vim.

While this is an obvious bug with `docker-machine` (I believe it's the SSH module that's causing this), VimR should handle this more gracefully. Perhaps it should launch bash with the `--noprofile` argument?

**Comment by richarddewit** [comment]
I get the following 2 logs on OS X 10.11.1:

> 1/14/16 11:52:19.540 AM VimR[19590]: Unknown class I in Interface Builder file at path /Applications/VimR.app/Contents/Resources/Base.lproj/MainMenu.nib.

> 1/14/16 11:52:19.620 AM VimR[19590]: objc[19590]: Class VRPlugin is implemented in both /Applications/VimR.app/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition and /Applications/VimR.app/Contents/PlugIns/Markdown.vimr-plugin/Contents/Frameworks/VimRPluginDefinition.framework/Versions/A/VimRPluginDefinition. One of the two will be used. Which one is undefined.

Then no screen is launched, the menu bar says `VimR` but other than that, nothing happens.

**Comment by hieonn** [comment]
OS X 10.11.1: VimR doesn't work at all. The menus are shown, and can be chosen but no reaction has been made. Is there any solution for it?
