### ISSUE TITLE
Slows to a crawl

### ISSUE THREAD

**Issue by DelvarWorld** [qvacua/vimr#180]
While working on a large project, VimR became slower and slower, to the point where there was half second - 1 second delay between typing and seeing keystrokes. MacVim on the same project has not exhibited such behavior.

**Comment by qvacua** [comment]
That's unfortunate... How many open files do you have?

**Comment by hrickards** [comment]
I just wondered if there was any progress on this issue? I've been using VimR as my text editor at work for the last couple of months, and the only way it's useable is to restart VimR every couple of hours. Otherwise (presumably because of a memory leak somewhere) it gets slower and slower to the point of being unuseable, and takes up more and more memory. This is an issue experienced across multiple machines, on both OSX Yosemite and El Capitan. I can provide any debugging info that would be helpful.

**Comment by qvacua** [comment]
No, not yet. Yes, debugging info would be definitely helpful.

**Comment by hrickards** [comment]
Okay, great. What specifically should I capture/provide? Thanks for the awesome vim wrapper by the way!

**Comment by camflan** [comment]
I have the same issue here, let me know what you'd like to see. Next time it happens, I'll try syntime, but is there anything else?
