### ISSUE TITLE
Use VimR for Git commit messages

### ISSUE THREAD

**Issue by alexbepple** [qvacua/vimr#190]
It seems impossible to use VimR for Git commit messages using `git commit` on the command line. VimR opens the `COMMIT_EDITMSG`, but `git commit` immediately exits with

    Aborting commit due to empty commit message.

I see that you use MacVim under the hood. With MacVim, everything works fine.

VimR Version 0.7.1 (29)
OS X Version 10.10.4

**Comment by lsd** [comment]
This is possible but requires some hacking to get working. I personally set my editor to `macvim -f` in my gitconfig for git commits.

If you install the VimR cli tool in the preferences pane and open it up, you'll notice it's a ruby script that uses `osascript` to call inline AppleScript. Ideally we would add a `--wait` param to this cmdline tool to tell it to wait until vimR closes before letting `git` continue.

On the command line OS X has `open` that accepts two important params.. `-n` which opens a new instance of the app even if one is already open and `-W` which waits until the instance is closed before moving on.

for example if you try: `open -W -b com.qvacua.VimR ~/repo/README.md` you'll notice on the commandline this command waits until the instance of VimR is closed. The problem is, the README.md file opens in an existing VimR instance, meaning the command will wait until the main VimR instance is closed (probably not what you want, since this is probably the VimR you're working in.)

so on my machine (10.11.2) I added the -n flag which should give the expected results. Instead, I get a new VimR instance but the README.md doesn't open.

`open -n -W -b com.qvacua.VimR ~/repo/README.md`

If I get a chance this week I'd like to refactor the vimr cmdline tool, at least for personal use.

See http://stackoverflow.com/a/24166673

**Comment by Jayphen** [comment]
Is this still not possible?

**Comment by qvacua** [comment]
You can add the following to `.gitconfig` under `[core]`
```
editor = vimr --wait --nvim
```
