### ISSUE TITLE
Support ligatures.

### ISSUE THREAD

**Issue by jordwalke** [qvacua/vimr#221]
> Is VimR's reboot going to include ligature support? MacVim recently added support.

* Add a checkbox in the Appearance preferences pane (turn off by default)
* Turn on/off ligatures in the preview text view in the Appearance preferences pane.

**Comment by qvacua** [comment]
Actually, the rewrite is (also) using the code from MacVim (snapshot 104) for string drawing: see [MMCoreTextView.m](https://github.com/qvacua/vimr/blob/master/SwiftNeoVim/MMCoreTextView.m) and [TextDrawer.m](https://github.com/qvacua/vimr/blob/master/SwiftNeoVim/TextDrawer.m). However, due to the update mechanism of NeoVim and how we use it, sometimes the ligatures may be broken, for instance when the second `=` of `==` is drawn in the next event loop then the first `=`. One has to think about how to mitigate this problem without issuing too many redraws. Also, I don't know what happens when the resulting glyph occupies less cells than the non-ligature-glyphs. Since I don't have any monospaced fonts with ligature support, I cannot test this. Are there any free ones available? If this feature is important for many I could of course buy one using Bountysource 😄...

**Comment by jordwalke** [comment]
I will be glad to donate more via Bounty Source. You can also download Fira for fee.

**Comment by qvacua** [comment]
Fira, got it.

**Comment by qvacua** [comment]
Wait for GH-213

**Comment by qvacua** [comment]
I don't know why I cannot turn off ligatures in the preview `NSTextView` for FiraCode... With Hasklig I don't have any problems... No no-ligatures-preview in the Preferences for FiraCode for now.

**Comment by Leonidas-from-XIV** [comment]
When using Iosevka I can see the ligatures in the preview window, but the main window does not use ligatures. Something seems to be still off. Using the latest release.

**Comment by qvacua** [comment]
Ligatures are turned off by default. You can activate it in Preferences -> Appearance -> Use Ligatures"

**Comment by Leonidas-from-XIV** [comment]
As said, I did and they are visible in the preview window but not in the editor:

<img width="485" alt="screen shot 2018-01-14 at 11 16 34" src="https://user-images.githubusercontent.com/121531/34914912-7a073644-f91c-11e7-9dcd-d7385a2a03bf.png">

**Comment by qvacua** [comment]
Ah ok. Could you create a new issue with your screenshot? It's probably a bug in rendering since some ligatures work. Thanks.
