### ISSUE TITLE
Latest snapshot does not work on 10.10.x?

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#318]
I just downloaded the latest snapshot (20161029.1904-117), and it won't open on my machine. The error message reads "You have OS X 10.10.5. The application requires OS X 10.11 or later."

I'm wondering if this is deliberate?

**Comment by qvacua** [comment]
That's very odd, I've been always building for 10.11 (El Capitan) from the very first snapshot. Since I don't have a machine with 10.10.x I cannot test. And because of that I'm afraid I cannot support 10.10.x...

Does https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.10.0-SNAPSHOT-20161025.2226-116 work for you?

However, this is a general problem. Currently, by chance, I've got two machines with 10.11 (private machine) and 10.12 (for work). Thus, I can "support" the older 10.11. However, soon or later, I'm going to merge the two, and will only be able to officially support the newest version of macOS or the version I'm going to use...

**Comment by telemachus** [comment]
No, that version doesn't work either.

The problem seems to be in `Info.plist` which has "Minimum system version" set to 10.11. When I look at the source code version, that seems to be set via `$(MACOSX_DEPLOYMENT_TARGET)` in the `Info.plist` in `VimR`. I guess I'm wondering whether you can't choose a lower deployment target, but I have to admit that I don't know much of anything about building GUIs on macOS.

**Comment by qvacua** [comment]
The deployment target was explicitly set to 10.11 due to the aforementioned reason. Try <http://taewon.de/VimR-Yosemite.tar.bz2>. I just set the deployment target to 10.10. If it works without any problems, I'll compile for 10.10 from now on, but only "officially" support >= 10.11.

**Comment by telemachus** [comment]
Thanks for clarifying. I completely understand that you can't offer official support, but I'm happy to say that that version works perfectly. If you don't mind resetting the deployment target, I'd very much appreciate it. Either way, thanks for running this experiment.

**Comment by qvacua** [comment]
Hm, I think for the time being I'll just build two separate packages for non-snapshot releases. Maybe I can use Travis to automatically build for 10.10. I'll keep you updated.

**Comment by qvacua** [comment]
From the next snapshot on, the builds will be built with deployment target 10.10.x.

**Comment by telemachus** [comment]
Thanks so much!
