### ISSUE TITLE
Build for mavericks

### ISSUE THREAD

**Issue by myybks** [qvacua/vimr#406]
Hi guys,

Tried VirmR on Capitan and really like it, is there a build for Mavericks available, or it is possible to build it for Mavericks?

Than you.

**Comment by qvacua** [comment]
No, there's no build for Mavericks. It is built for 10.10, but I can only test it on my machine with 10.12...

**Comment by mybks** [comment]
@qvacua Thank you for your answer, may I ask you if it's possible to build it for mavericks manually?

Thank you

**Comment by qvacua** [comment]
What you can try:

- clone the repo
- open the Xcode project on 10.12 (since VimR can only be compiled by the newest Xcode...)
- set the deployment target to Maverick
- follow the how to build steps on README

But I guess that some of Cocoa-API-calls within VimR are not compatible with Mavericks... If you don't have to use neovim, then [MacVim](https://github.com/macvim-dev/macvim/releases) is compiled for macOS from 10.8 on (and is more stable than VimR... 😬)

**Comment by mybks** [comment]
@qvacua Thank you very much for your help, I really like the filebrowser of VimR, NERDTree is not so cool :) Will try to compile it as you suggested. Thank you.

**Comment by romaninsh** [comment]
@myybks did you manage to build it? Have you had any problems?

**Comment by myybks** [comment]
@romaninsh I've updated osx, don't have this problem anymore, it turned out to be not that bad :)

**Comment by qvacua** [comment]
Thanks for the update, closing...
