### ISSUE TITLE
Feature request: open file by dragging into the main window

### ISSUE THREAD

**Issue by gynet** [qvacua/vimr#458]
It would be nice add support to open file by dragging

**Comment by qvacua** [comment]
You can already drag and drop on the VimR icon to open files. Do you mean something else?

**Comment by gynet** [comment]
I mean drag files to the app **panel**. It's currently not working on my side

**Comment by UmkaDK** [comment]
I kind off agree with @gynet. It would be a nice addition if you could drag-n-drop a file from the Finder (or even the Files tool) into vim's window. I guess the default behaviour could be to do what ever happens when you drop a file onto the dock icon (which is already implemented).

But this feature would come into it's own if we could control how a dropped file is opened, ie: open in a new tab vs open in a new buffer of the same window. This way, when working with split windows, a user could drag-n-drop a file on to the actual window where they want that file to be loaded. This would be very handy indeed!

**Comment by lsd** [comment]
The implemented behavior is native os x

**Comment by qvacua** [comment]
@gynet @UmkaDK @lsd Yes, the drag&drop onto the window is not yet implemented. However, distinguishing between different splits would be quite difficult, I guess...

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F214 (thanks to @nhtzr)

**Comment by gynet** [comment]
@qvacua  I tried the SNAPSHOT-214, it is working, however, the latest release/snapshot version is not working, is there any regression or not merged yet?

**Comment by gynet** [comment]
@qvacua please reopen this issue.  @nhtzr

**Comment by wookayin** [comment]
This is not working as of 2018!

**Comment by qvacua** [comment]
The newest release has this fixed. https://github.com/qvacua/vimr/releases/tag/v0.26.5-308
