### ISSUE TITLE
Resize window without obscuring window with emoji and dimensions

### ISSUE THREAD

**Issue by kcmannem** [qvacua/vimr#614]
I really dislike the window resize behaviour. I need a view of my code to resize to the exact spot. Currently that stupid emoji view comes in the way and I'll have to do the resize action a few extra times to get it to the exact point I want it at.

**Comment by UmkaDK** [comment]
I agree with the notion of "it would be nice to see the code while resizing the window", but the point could have been made in a much nicer way. At the end of the day, @qvacua and the contributors are working on the project for free and on their own time.

**Comment by qvacua** [comment]
@kcmannem: as @UmkaDK said, your wording needs quite a polish. Well, that emoji display instead of live resizing was introduced due to performance reasons. However, as a matter of fact, it was also bugging me since then. I think I'll just make it an option and when, eventually, the drawing is optimized enough, I'll make it the default.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F264 : you'll find a checkbox in the Advanced preferences.

**Comment by kcmannem** [comment]
@qvacua apologies, I didn't mean for a bad tone. I wrote this in a very casual tone (as I would have submitted a ticket on my own project when something needs to be fixed). Like I said in my email to you, I use vimr everyday and appreciate the work you put in.

**Comment by qvacua** [comment]
Ah, you are the one who wrote the mail! ;)
