### ISSUE TITLE
Pass all env vars to nvim when launching using `vimr` (would result in VirtualEnv support)

### ISSUE THREAD

**Issue by JamoBox** [qvacua/vimr#625]
I could not seem to find a way to get vimr to respect virtual environments. Usually if I am working on a python project and have a virtual environment set up with venv, running vim and then running `:!source bin/activate` will set the virtual environment within vim.

This did not seem to work with vimr (launching from dock, then running the source command), as the python version stays as my system's one, and none of the venv libraries are in my python path.

**Comment by SkyLeach** [comment]
the vimr program isn't following best practices with the shebang line.  The Vimr.app doesn't have access to anything but the system shell.  In order to bootstrap into a virtualenv, modify the generated vimr script first line by changing `#!/usr/bin/python` to `#!/usr/bin/env python`.  This will cause bootstrap to add in the python environment from the virtualenv python and make things work.

Took me a while to figure this out because it was causing all of my lexer plugins to be unable to find my virtualenv classes and thus breaking my whole IDE.

**Comment by SkyLeach** [comment]
It's also not compatible with python3 environments.  I'm about to issue a PR to fix that, but I have to integrate my altered vimr script

**Comment by SkyLeach** [comment]
Well, it seems that this issue is related to the VimR.app and bootstrap still works provided that you kill the app and use the console script to open it (even the old one).

The new script works fine, but isn't really required (and doesn't really fix anything) so I'm not issuing a PR unless there is a pressing need.

**Comment by qvacua** [comment]
If we want to pass the whole set of environment variables, we have to change how we launch the background `nvim` process.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F283 (you have to re-install `vimr`)

**Comment by qvacua** [comment]
`vimr --cur-env` will create a new window with the current environment variables.

**Comment by blochberger** [comment]
Looks like there is a regression. When using SNAPSHOT-20201224.200216 and starting with `vimr --cur-env` the environment is not correctly passed. Invoking `:!env` inside VimR does not show the same environment as from which `vimr --cur-env` was launched.

Simply starting `nvim` works fine.
