### ISSUE TITLE
NeoVim :CheckHealth terminal component fails

### ISSUE THREAD

**Issue by hakamadare** [qvacua/vimr#656]
running `:CheckHealth` from within VimR produces the following output:

```
health#nvim#check
========================================================================
...
## terminal
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
...
```

running the same command from `nvim` in the terminal produces the following output:

```health#nvim#check
 ========================================================================
  ## Configuration
...
## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'
...
```

I can imagine working around this with `~/.MacOS/environment.plist` if that still works, but ideally I'd like VimR to make $TERM a user-configurable variable.

**Comment by qvacua** [comment]
Does the failing check break something? As a workaround you can use `--cur-env` option of `vimr` (introduced in the latest snapshot 283)

**Comment by hakamadare** [comment]
@qvacua The Neovim wiki mentions [some problems](https://github.com/neovim/neovim/wiki/FAQ#home-or-some-other-special-key-doesnt-work) caused by an incorrectly set $TERM.

Using `--cur-env` does provide a workaround.

**Comment by cweagans** [comment]
This does not appear to be resolved. If I run `vimr` from the command line, everything works just fine, but if I start VimR.app from Alfred or whatever, this check still fails.

I don't think inheriting the TERM variable from your terminal is necessarily the right thing, given that whatever your TERM is set to is not applicable to the way that VimR actually renders Neovim. Could VimR override this variable for graphical sessions instead of having undefined behavior?
