### ISSUE TITLE
LSP signatures changed, new snapshot needed

### ISSUE THREAD

**Issue by bmulholland** [qvacua/vimr#870]
On latest snapshot SNAPSHOT-20210703.151310

Trying to use some LSPs will throw an error:

```
Error executing vim.schedule lua callback: ...w.bundle/Contents/Resources/runtime/lua/vim/lsp/util.lua:271: Number is not integral
```

That's because the LSP handler signatures changed: https://old.reddit.com/r/neovim/comments/pk85w9/error_executing_vimschedule_lua_callback/

The same error doesn't happen when running neovim outside of vimr.

Fix is releasing a new snapshot with the latest neovim included.

**Comment by jarredbarber** [comment]
this has completely broken VimR for me :/ is it possible to decouple VimR from specific neovim versions to prevent these types of problems in the future?

**Comment by bmulholland** [comment]
Yeah FWIW I've switched off of VimR because of this. I still prefer VimR over other options I've found, but blockers are blockers.

**Comment by imkerberos** [comment]
wait for update.

**Comment by clason** [comment]
These changes are also in the latest stable release 0.5.1, so arguably a new stable release built against that is needed.

(And, no, it's not possible to decouple VimR; the architecture is intrinsically linked to embedding a -- patched -- `libnvim` rather than communicating with an external `neovim` process via RPC. Somebody would have to fork VimR and do a significant rewrite to switch to the latter.)

**Comment by imajes** [comment]
@imkerberos i think it's fair to also point out that you've made _other_ changes to the project also...

**Comment by imkerberos** [comment]
@imajes There are only 6 commits in the forked repository, you can check it.

**Comment by azzsh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在忙，无法及时回复您的邮件。将尽快给您回复。
