### ISSUE TITLE
fresh install in dark mode issues

### ISSUE THREAD

**Issue by JeanBlignaut** [qvacua/vimr#908]
As a fellow coder I appreciate that a color issue might not be your top priority,
however as a new users firs impression of your editor, I can't help but form instant opinions of the stability based on the color issue 

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/76569735/155020706-437b49a7-769e-4da8-a203-a957c4691464.png">

I realise that this probably duplicates #878 and #859 but thought it worthwhile to log regardless.

**Comment by qvacua** [comment]
Currently, VimR does not support dark mode. My assumption is that most Neovim users use custom color scheme anyways. Therefore, it can adapt to the color scheme you have selected in Neovim.  Turn on Preferences -> Appearance -> Use Neovim's color scheme for main window and tools.

Closing the issue, please feel free to discuss the issue further here 😀

**Comment by qvacua** [comment]
The idea proposed in #859 is nice. I'll try to implement it.

**Comment by j-rahman** [comment]
Why is this issue closed? I just installed a fresh copy of vimr (`v. 0.44.0,20230103.174333`) and, since I predominantly use Dark Mode, the Preferences window just looks bad and half-baked because of this unresolved very real issue. Since this app purports to be a native Swift app built for macOS, I would expect it to look more than half decent and to support automatic Dark Mode switching off the shelf. Thank you.
